--- #YAML:1.0
name:               Net-OperaLink
version:            0.04
abstract:           ~
author:
    - Opera Software ASA <cpan@opera.com>
license:            BSD
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    CGI:             0
    feature:         0
    JSON::XS:        0
    LWP::UserAgent:  0
    Net::OAuth:      0.19
    Test::More:      0
    URI:             0
resources:
    bugtracker:  https://bugs.opera.com
    repository:  http://github.com/operasoftware/perl5-net-operalink
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
